---

- hosts: localhost
  gather_facts: False
  tasks:

    # =================================                 Brew Prerequisites
    - name: Install Prerequisites for Brew
      apt:
        name: "{{ item }}"
        update_cache: yes
      with_items:
        - build-essential
        - curl
        - file
        - python-setuptools
        - ruby
      sudo: yes
      tags:
        - install-brew

    # =================================                       Install Brew
    - name: Install Brew
      shell: ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install)"
      tags:
        - install-brew

    # =================================                     Configure Brew
    - name: Configure Brew
      lineinfile:
        dest: ~/.bashrc
        line: "{{ item }}"
      with_items:
        - export PATH="/home/linuxbrew/linuxbrew/.linuxbrew/bin:$PATH"
        - export MANPATH="/home/linuxbrew/.linuxbrew/share/man:$MANPATH"
        - export INFOPATH="/home/linuxbrew/.linuxbrew/share/info:$INFOPATH"
      tags:
        - install-brew

    # =================================               Install Common Taps
    - name: Installing Common Taps
      command: brew tap {{ item }}
      with_items:
        - homebrew/core
        - homebrew/services
        - homebrew/versions
        - homebrew/completions
        - homebrew/bundle
        - homebrew/nginx
        - homebrew/science
        - homebrew/aliases
      tags:
        - install-brew
