# Add apt repository
- apt_repository:
    repo: "{{ item }}"
  with_items:
    - ppa:linuxgndu/sqlitebrowser-testing
  become: yes

- name: Install Development Apps
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - sqlitebrowser
    - vagrant
  become: yes
