 Add apt repository
- apt_repository:
    repo: "{{ item }}"
  with_items:
    - ppa:dreibh/ppa
  become: yes

- name: Install Networking Apps
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - wireshark
  become: yes
