---

- hosts: localhost
  gather_facts: False
  tasks:

    # ====================================================        Zsh Prerequisites
    - name: Install Prerequisites for Zsh
      apt:
        name: "{{ item }}"
        update_cache: yes
      with_items:
        - git
        - git-core
        - zsh
      sudo: yes
      tags:
        - install-zsh

    - name: Create .zshrc file
      file:
        path: ~/.zshrc
        state: touch

    # ====================================================              Install Zsh
    - name: Installing Zsh
      command: brew install {{ item }}
      with_items:
        - zsh
        - zsh-lovers
        - z
        - zsh-completions
        - zsh-syntax-highlighting
        - zsh-autosuggestions
        - zsh-git-prompt
        - zsh-history-substring-search
      tags:
        - install-zsh

    # ====================================================        Install oh-my-zsh
    - name: Installing oh-my-zsh
      shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
      sudo: yes
      tags:
        - install-zsh


    # ====================================================           Configure Brew
    - name: Configure Brew Path
      lineinfile:
        dest: ~/.zshrc
        line: "{{ item }}"
      with_items:
        - export PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"
        - export MANPATH="/home/linuxbrew/.linuxbrew/share/man:$MANPATH"
        - export INFOPATH="/home/linuxbrew/.linuxbrew/share/info:$INFOPATH"
      tags:
        - install-zsh

    # ====================================================        Configure Plugins
    - name: Configure Zsh Plugins
      lineinfile:
        dest: ~/.zshrc
        regexp: ^plugins=
        line: "plugins=(git brew ruby sudo z)"
      tags:
        - install-zsh


    # ====================================================        Configure Plugins
    - name: Configure Zsh Completions
      lineinfile:
        dest: ~/.zshrc
        line: "fpath=(/home/linuxbrew/.linuxbrew/share/zsh-completions $fpath)"
      tags:
        - install-zsh


    # ====================================================        Configure Plugins
    - name: Configure Zsh Syntax Highlighting
      lineinfile:
        dest: ~/.zshrc
        line: "source /home/linuxbrew/.linuxbrew/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
      tags:
        - install-zsh

    # ====================================================        Configure Plugins
    - name: Configure Zsh Auto Suggestions
      lineinfile:
        dest: ~/.zshrc
        line: "source /home/linuxbrew/.linuxbrew/share/zsh-autosuggestions/zsh-autosuggestions.zsh"
      tags:
        - install-zsh

    # ====================================================        Configure Plugins
    - name: Change Zsh Theme
      lineinfile:
        dest: ~/.zshrc
        regexp: 'robbyrussell'
        replace: 'pygmalion'
      tags:
        - install-zsh

    # ====================================================        Install oh-my-zsh
    - name: Create .z File for z
      shell: if [ ! -f "~/.z" ]; then touch "$HOME/.z"; fi
      tags:
        - install-zsh
