# ====================================================  Install via apt-get
- name: Install Common System Tools (apt-get)
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - python-pip
    - sshpass
    - terminator
    - vim
    - htop
  become: yes

# ====================================                     Install via brew
- name: Install Common System Tools (brew)
  command: brew install {{ item }}
  with_items:
    - pkgdiff
    - translate-shell
    - tree
    - sqlite

# ====================================                     Install via brew
- name: Install Common System Tools (pip)
  pip:
    name: requests
