# ====================================================  Change git user name
- git_config:
    name: user.name
    scope: global
    value: {{ git_username }}

# ====================================                  Change git user email
- git_config:
    name: user.email
    scope: global
    value: {{ git_user_email }}

# ====================================                  Set auto color
- git_config:
    name: color.ui
    scope: global
    value: true
