---

- set_fact: os_user_name="{{ lookup('env','USER') }}"
  register: user
- debug:
    msg: "Current user is {{user}}"


- include: common.yml
  tags: [common]

- include: brew.yml
  tags: [brew]

- include: zsh.yml
  tags: [zsh]
