---

- set_fact: os_user_name="{{ lookup('env','USER') }}"
  register: user
- debug:
    msg: "Current user is {{user}}"

- include: brew.yml
  tags: [brew]

- include: common.yml
  tags: [common]

- include: zsh.yml
  tags: [zsh]

- include: git.yml
  tags: [git]

- include: jekyll.yml
  tags: [jekyll]
